version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db
  frontend:
    build: ./frontend
    ports:
      - "5173:80"
    env_file:
      - .env
  db:
    image: postgres:13
    environment:
      POSTGRES_URL: ${DATABASE_URL}
    ports:
      - "5432:5432"